"""Initial migration

Revision ID: add10f0f6d63
Revises:
Create Date: 2025-09-27 18:57:13.652115

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add10f0f6d63"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "master_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.String(), nullable=True),
        sa.Column("encounter_type", sa.String(), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=True),
        sa.Column("national_id", sa.String(), nullable=True),
        sa.Column("member_id", sa.String(), nullable=True),
        sa.Column("facility_id", sa.String(), nullable=True),
        sa.Column("unique_id", sa.String(), nullable=True),
        sa.Column("diagnosis_codes", sa.Text(), nullable=True),
        sa.Column("service_code", sa.String(), nullable=True),
        sa.Column("paid_amount_aed", sa.Float(), nullable=True),
        sa.Column("approval_number", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("error_explanation", sa.Text(), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_master_table_claim_id"), "master_table", ["claim_id"], unique=True)
    op.create_index(op.f("ix_master_table_id"), "master_table", ["id"], unique=False)
    op.create_table(
        "metrics_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("claim_count", sa.Integer(), nullable=True),
        sa.Column("total_paid_amount", sa.Float(), nullable=True),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metrics_table_error_type"),
        "metrics_table",
        ["error_type"],
        unique=False,
    )
    op.create_index(op.f("ix_metrics_table_id"), "metrics_table", ["id"], unique=False)
    op.create_table(
        "refined_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.String(), nullable=True),
        sa.Column("encounter_type", sa.String(), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=True),
        sa.Column("national_id", sa.String(), nullable=True),
        sa.Column("member_id", sa.String(), nullable=True),
        sa.Column("facility_id", sa.String(), nullable=True),
        sa.Column("unique_id", sa.String(), nullable=True),
        sa.Column("diagnosis_codes", sa.Text(), nullable=True),
        sa.Column("service_code", sa.String(), nullable=True),
        sa.Column("paid_amount_aed", sa.Float(), nullable=True),
        sa.Column("approval_number", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("error_explanation", sa.Text(), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refined_table_claim_id"), "refined_table", ["claim_id"], unique=True)
    op.create_index(op.f("ix_refined_table_id"), "refined_table", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refined_table_id"), table_name="refined_table")
    op.drop_index(op.f("ix_refined_table_claim_id"), table_name="refined_table")
    op.drop_table("refined_table")
    op.drop_index(op.f("ix_metrics_table_id"), table_name="metrics_table")
    op.drop_index(op.f("ix_metrics_table_error_type"), table_name="metrics_table")
    op.drop_table("metrics_table")
    op.drop_index(op.f("ix_master_table_id"), table_name="master_table")
    op.drop_index(op.f("ix_master_table_claim_id"), table_name="master_table")
    op.drop_table("master_table")
    # ### end Alembic commands ###
